import {
  Categories,
  Filters,
  Subcategories,
} from "#database/scripts/seeders/categories/constants";
import { pgEnum } from "drizzle-orm/pg-core";

export const conditionsEnum = pgEnum("conditions", ["new", "used", "damaged"]);
export const statusEnum = pgEnum("status", ["available", "sold"]);
export const deliveryMethodEnum = pgEnum("delivery_method", [
  "shipping",
  "pickup",
]);
export const sexEnum = pgEnum("sex", ["male", "female"]);
export const profileEnum = pgEnum("profile_types", ["private", "professional"]);

export const filtersEnum = pgEnum("filters", [
  Filters.CONDITION,
  Filters.GENDER,
  Filters.COLOR,
  Filters.MATERIAL_CLOTHING,
  Filters.SIZE_CLOTHING,
  Filters.SIZE_SHOES,
  Filters.SIZE_WATCHES,
  Filters.SIZE_PHONE_SCREEN,
  Filters.SIZE_MONITOR_SCREEN,
]);

export const filterTypeEnum = pgEnum("filter_types", [
  "select",
  "boolean",
  "text",
  "number",
  "range",
]);

export const categoriesEnum = pgEnum("categories", [
  Categories.ELECTRONICS,
  Categories.CLOTHINGS,
  Categories.KIDS,
  Categories.COLLECTABLES,
]);

export const SubcategoriesEnum = pgEnum("subcategories", [
  Subcategories.COMPUTERS,
  `${Subcategories.ACCESSORIES}-${Subcategories.COMPUTERS}`,
  `${Subcategories.ACCESSORIES}-${Categories.CLOTHINGS}`,
  Subcategories.LAPTOPS,
  Subcategories.DESKTOP_COMPUTER,
  Subcategories.PHONES,
  `${Subcategories.ACCESSORIES}-${Subcategories.PHONES}`,
  Subcategories.SMARTPHONES_CELLULARS,
  Subcategories.ACCESSORIES,
  Subcategories.PHOTOGRAPHY,
  `${Subcategories.ACCESSORIES}-${Subcategories.PHOTOGRAPHY}`,
  Subcategories.CAMERAS,
  Subcategories.LENSES,
  Subcategories.SHOES,
  Subcategories.JEANS,
  Subcategories.PANTS,
  Subcategories.TOYS,
  Subcategories.BOOK_KIDS,
  Subcategories.CARDS,
  Subcategories.SINGLE_CARDS,
  Subcategories.UNCUT_PAPER_SHEET,
]);

export const FilterValuesEnum = pgEnum("filter_values", [
  // CONDITIONS
  "new",
  "used-like-new",
  "used-good",
  "used-fair",
  // GENDER
  "unisex",
  "men",
  "women",
  // CLOTHING MATERIALS
  "leather",
  "cotton",
  "wool",
  "silk",
  "linen",
  "polyester",
  "nylon",
  "rayon",
  "spandex",
  "acrylic",
  "viscose",
  "denim",
  "suede",
  "velvet",
  "cashmere",
  "corduroy",
  "tweed",
  "flannel",
  "canvas",
  "hemp",
  "bamboo",
  "fleece",
  "microfiber",
  "modal",
  "jacquard",
  "chiffon",
  "taffeta",
  "satin",
  "gabardine",
  "terrycloth",
  "seersucker",
  "batiste",
  "muslin",
  "organza",
  "tulle",
  // COLORS
  "black",
  "white",
  "red",
  "blue",
  "yellow",
  "green",
  "orange",
  "purple",
  "pink",
  "brown",
  "gray",
  "beige",
  "cyan",
  "magenta",
  "lime",
  "olive",
  "navy",
  "teal",
  "maroon",
  "turquoise",
  "gold",
  "silver",
  "bronze",
  "ivory",
  "mustard",
  "coral",
  "salmon",
  "peach",
  "lavender",
  "charcoal",
  "indigo",
  "periwinkle",
  "burgundy",
  "mint",
  "ochre",
  "plum",
  "rust",
  "saffron",
  "jade",
  "violet",
  // CLOTH SIZES
  "s",
  "m",
  "l",
  "xl",
  "xxl",
  "xxxl",
  // SHOES SIZES
  "35",
  "35.5",
  "36",
  "36.5",
  "37",
  "37.5",
  "38",
  "38.5",
  "39",
  "39.5",
  "40",
  "40.5",
  "41",
  "41.5",
  "42",
  "42.5",
  "43",
  "43.5",
  "44",
  "44.5",
  "45",
  "45.5",
  "46",
  "46.5",
  "47",
  "47.5",
  "48",
  "48.5",
  "49",
  "49.5",
  "50",
  // WATCH WIRST SIZES
  "28mm",
  "30mm",
  "32mm",
  "34mm",
  "36mm",
  "38mm",
  "40mm",
  "41mm",
  "42mm",
  "43mm",
  "44mm",
  "45mm",
  "46mm",
  "47mm",
  "48mm",
  "50mm",
  "52mm",
  // PHONE SIZE SCREENS
  '3.5"',
  '4.0"',
  '4.5"',
  '5.0"',
  '5.2"',
  '5.5"',
  '5.7"',
  '6.0"',
  '6.1"',
  '6.2"',
  '6.3"',
  '6.4"',
  '6.5"',
  '6.6"',
  '6.7"',
  '6.8"',
  '7.0"',
  '7.2"',
  '7.6"',
  '8.0"',
  // MONITOR SIZE SCREENS
  '15"',
  '17"',
  '19"',
  '20"',
  '21"',
  '21.5"',
  '22"',
  '23"',
  '23.6"',
  '24"',
  '25"',
  '27"',
  '28"',
  '29"',
  '30"',
  '32"',
  '34"',
  '35"',
  '37.5"',
  '38"',
  '40"',
  '42"',
  '43"',
  '49"',
  '55"',
]);
