name: tantovale
services:
  storefront:
    container_name: tv_storefront
    build:
      context: .
      dockerfile: ./apps/storefront/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - app_network

  server:
    container_name: tv_server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: unless-stopped
    ports:
      - 4000:4000
    networks:
      - app_network

networks:
  app_network:
    name: tantovale_network
    labels:
      'com.docker.compose.project': 'tantovale'
