import { parseEnv, type Environment } from '../env';

export const authPath = 'auth';
export const cronPath = 'cron';

export const DEFAULT_ACCESS_TOKEN_EXPIRES = () => new Date(Date.now() + 24 * 60 * 60 * 1000); // 24 hours from now

export const DEFAULT_REFRESH_TOKEN_EXPIRES = () => new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); // 7 days from now

export const DEFAULT_EMAIL_ACTIVATION_TOKEN_EXPIRES = () => new Date(Date.now() + 60 * 60 * 1000); // 60 minutes from now

export const DEFAULT_ACCESS_TOKEN_EXPIRES_IN_MS = () => Math.floor(Date.now() / 1000) + 24 * 60 * 60; // 24 hours in seconds

export const DEFAULT_REFRESH_TOKEN_EXPIRES_IN_MS = () => Math.floor(Date.now() / 1000) + 7 * 24 * 60 * 60; // 7 days in seconds

export const DEFAULT_EMAIL_ACTIVATION_TOKEN_EXPIRES_IN_MS = () => Math.floor(Date.now() / 1000) + 60 * 60; // 60 minutes in seconds

export const SHIPPING_UNITS = {
	MASS: 'kg',
	DISTANCE: 'cm',
} as const;

export const SHIPPING_ERROR_MESSAGES = {
	SHIPPING_DIMENSIONS_NOT_FOUND: 'Shipping dimensions not found',
	SHIPPING_CALCULATION_FAILED: 'Failed to calculate shipping cost',
} as const;

export function getNodeEnvMode(env: string) {
	return {
		isDevelopmentMode: env === 'development',
		isTestMode: env === 'test',
		isStagingMode: env === 'staging',
		isProductionMode: env === 'production',
	};
}

const env = parseEnv(process.env);

export const environment: Environment = {
	PROJECT_NAME: env.PROJECT_NAME,
	NODE_ENV: env.NODE_ENV,
	NEXT_PUBLIC_HONO_API_URL: env.NEXT_PUBLIC_HONO_API_URL,
	LOG_LEVEL: env.LOG_LEVEL,

	STOREFRONT_HOSTNAME: env.STOREFRONT_HOSTNAME,
	STOREFRONT_PORT: env.STOREFRONT_PORT,
	SERVER_HOSTNAME: env.SERVER_HOSTNAME,
	SERVER_PORT: env.SERVER_PORT,

	POSTGRES_USER: env.POSTGRES_USER,
	POSTGRES_PASSWORD: env.POSTGRES_PASSWORD,
	DATABASE_HOST: env.DATABASE_HOST,
	DATABASE_PORT: env.DATABASE_PORT,
	POSTGRES_DB: env.POSTGRES_DB,

	PAYMENT_PROVIDER_API_URL: env.PAYMENT_PROVIDER_API_URL,
	PAYMENT_PROVIDER_API_VERSION: env.PAYMENT_PROVIDER_API_VERSION,
	PAYMENT_PROVIDER_SECRET_KEY: env.PAYMENT_PROVIDER_SECRET_KEY,
	PAYMENT_PROVIDER_CLIENT_ID: env.PAYMENT_PROVIDER_CLIENT_ID,
	PAYMENT_PROVIDER_CLIENT_SECRET: env.PAYMENT_PROVIDER_CLIENT_SECRET,
	PAYMENT_PROVIDER_PAY_PAGE_URL: env.PAYMENT_PROVIDER_PAY_PAGE_URL,
	PAYMENT_PROVIDER_WEBHOOK_SECRET: env.PAYMENT_PROVIDER_WEBHOOK_SECRET,
	POST_PAYMENT_REDIRECT_URL: env.POST_PAYMENT_REDIRECT_URL,

	SHIPPING_PROVIDER_SECRET_KEY: env.SHIPPING_PROVIDER_SECRET_KEY,
	SHIPPING_PROVIDER_WEBHOOK_SECRET: env.SHIPPING_PROVIDER_WEBHOOK_SECRET,

	AWS_REGION: env.AWS_REGION,
	AWS_BUCKET_NAME: env.AWS_BUCKET_NAME,
	AWS_ACCESS_KEY: env.AWS_ACCESS_KEY,
	AWS_SECRET_ACCESS_KEY: env.AWS_SECRET_ACCESS_KEY,

	ACCESS_TOKEN_SECRET: env.ACCESS_TOKEN_SECRET,
	REFRESH_TOKEN_SECRET: env.REFRESH_TOKEN_SECRET,
	EMAIL_VERIFY_TOKEN_SECRET: env.EMAIL_VERIFY_TOKEN_SECRET,
	RESET_TOKEN_SECRET: env.RESET_TOKEN_SECRET,
	COOKIE_SECRET: env.COOKIE_SECRET,

	SMTP_HOST: env.SMTP_HOST,
	SMTP_PORT: env.SMTP_PORT,
	SMTP_USER: env.SMTP_USER,
	SMTP_PASS: env.SMTP_PASS,

	DAILY_ORDER_CHECK_SECRET_KEY: env.DAILY_ORDER_CHECK_SECRET_KEY,
	DAILY_ORDER_PROPOSALS_CHECK_SECRET_KEY: env.DAILY_ORDER_PROPOSALS_CHECK_SECRET_KEY,
	TRANSACTIONS_SYNC_SECRET_KEY: env.TRANSACTIONS_SYNC_SECRET_KEY,

	PROPOSALS_HANDLING_TOLLERANCE_IN_HOURS: env.PROPOSALS_HANDLING_TOLLERANCE_IN_HOURS,
	ORDERS_PAYMENT_HANDLING_TOLLERANCE_IN_HOURS: env.ORDERS_PAYMENT_HANDLING_TOLLERANCE_IN_HOURS,
};
