import type { DescribeRouteOptions } from 'hono-openapi';
import {
	jsonEntityListSchema,
	positiveIntegerSchema,
	queryParameter,
	routeDescription,
	type ManualSchema,
} from '../common';

const locationSchema: ManualSchema = {
	type: 'object',
	properties: {
		id: positiveIntegerSchema,
		name: { type: 'string' },
		country_code: { type: 'string' },
		state_code: { type: 'string' },
		country_id: positiveIntegerSchema,
	},
	required: ['id', 'name'],
	additionalProperties: true,
};

export const catalogOpenApi = {
	categories: routeDescription({
		method: 'GET',
		path: '/categories',
		summary: 'List categories',
		tag: 'Catalog',
		security: 'public',
		errors: [404, 500],
		responseSchema: jsonEntityListSchema,
	}),
	locationSearch: routeDescription({
		method: 'GET',
		path: '/locations/search',
		summary: 'Search locations',
		tag: 'Catalog',
		security: 'public',
		errors: [400, 500],
		parameters: [
			queryParameter('locationType', 'Location kind.', { type: 'string', enum: ['city', 'province'] }),
			queryParameter('locationName', 'Location search text.'),
			{ ...queryParameter('locationCountryCode', 'ISO country code.'), required: false },
			{ ...queryParameter('locationStateCode', 'Optional state code.'), required: false },
		],
		responseSchema: { type: 'array', items: locationSchema, maxItems: 10 },
	}),
	locationById: routeDescription({
		method: 'GET',
		path: '/locations/search_by_id/:locationType/:locationId',
		summary: 'Get a location by type and ID',
		tag: 'Catalog',
		security: 'public',
		errors: [400, 404, 500],
		responseSchema: {
			type: 'object',
			properties: {
				locationResponse: {
					type: 'object',
					properties: {
						id: positiveIntegerSchema,
						name: { type: 'string' },
						stateCode: { type: 'string' },
					},
					required: ['id', 'name', 'stateCode'],
					additionalProperties: false,
				},
			},
			required: ['locationResponse'],
			additionalProperties: false,
		},
	}),
	property: routeDescription({
		method: 'GET',
		path: '/properties/:id',
		summary: 'Get a property',
		tag: 'Catalog',
		security: 'public',
		errors: [400, 404, 500],
		responseSchema: jsonEntityListSchema,
	}),
	properties: routeDescription({
		method: 'GET',
		path: '/properties/subcategory_properties/:id',
		summary: 'List subcategory properties',
		tag: 'Catalog',
		security: 'public',
		errors: [400, 404, 500],
		responseSchema: jsonEntityListSchema,
	}),
	subcategories: routeDescription({
		method: 'GET',
		path: '/subcategories',
		summary: 'List subcategories',
		tag: 'Catalog',
		security: 'public',
		errors: [404, 500],
		responseSchema: jsonEntityListSchema,
	}),
	subcategory: routeDescription({
		method: 'GET',
		path: '/subcategories/:id',
		summary: 'Get a subcategory',
		tag: 'Catalog',
		security: 'public',
		errors: [400, 404, 500],
		responseSchema: jsonEntityListSchema,
	}),
	subcategoryWithoutParent: routeDescription({
		method: 'GET',
		path: '/subcategories/no_parent/:id',
		summary: 'List subcategories without the parent',
		tag: 'Catalog',
		security: 'public',
		errors: [400, 404, 500],
		responseSchema: jsonEntityListSchema,
	}),
	subcategoryProperty: routeDescription({
		method: 'GET',
		path: '/subcategory_properties/:id',
		summary: 'Get subcategory property mappings',
		tag: 'Catalog',
		security: 'public',
		errors: [400, 404, 500],
		responseSchema: jsonEntityListSchema,
	}),
	subcategoryFilters: routeDescription({
		method: 'GET',
		path: '/subcategory_properties/filter/:id',
		summary: 'Get subcategory filters',
		tag: 'Catalog',
		security: 'public',
		errors: [400, 404, 500],
		responseSchema: jsonEntityListSchema,
	}),
} satisfies Record<string, DescribeRouteOptions>;
