name: Daily Orders Check

on:
  schedule:
    - cron: '0 5 * * *' # Every day at 5:00 UTC
  workflow_dispatch: # optional, to run manually

jobs:
  ping-cron-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Call Hono endpoint
        run: |
          curl -s -X GET "https://${{ secrets.SERVER_HOSTNAME }}/orders/cron/expired-orders-check?key=${{ secrets.DAILY_ORDER_CHECK_SECRET_KEY }}"
