name: Build & Deploy CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build's
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Enable Corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.10.0 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build server
        run: pnpm --filter @workspace/server... run build

      - name: Build frontend
        run: pnpm --filter @workspace/storefront... run build
